// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fatllopkueygoocnupam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdGxsb3BrdWV5Z29vY251cGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNTEwNjAsImV4cCI6MjA1NDgyNzA2MH0.z9ylPsFSPV2jI7r98znHHbtMhP3iqzxv91MTU4st-CI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);